### ISSUE TITLE
As a user, I want to know if there is an error when I use the page and to be notified if the page is loading (and has not seen an error)  

### ISSUE THREAD

**Issue by zhen0** [codecapstone/codealoud#137]
Sub tasks:
- [ ] Error status in admin, problem and lesson store - #141
- [ ] Error status check and message in admin page, code view page, user stats page - #140
- [ ] loading status for all major components (especially the code-sandbox page) - #139
- [ ] text color for error messages in auth - #138
